export const SIGN_IN = 'SIGN_IN'
export const SIGN_UP = 'SIGN_UP/DEFAULT'
export const OAUTH = 'OAUTH'
export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_ME = 'FETCH_ME'
export const CREATE_POST = 'CREATE_POST'
export const UPDATE_USER = 'UPDATE_USER'

export const SET_ME = 'SET_ME'
export const SET_POSTS = 'SET_POSTS'
export const SET_SUBMITTING_STATUS = 'SET_SUBMITTING_STATUS'
export const SET_USER = 'SET_USER'
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS'
